<div class="advantages">
    <div class="advantage shipping">
        <div class="icon">
            <img src="<?php echo $block->getViewFileUrl('images/delivery-truck-icon.png'); ?>" alt="<?php echo $this->escapeHtml(__('delivery-truck')); ?>">
        </div>
        <div class="description">
            <h4><?php echo __('Worldwide Shipping'); ?></h4>
            <p><?php echo __('Our Confident Client'); ?></p>
        </div>
    </div>
    <div class="advantage payment">
        <div class="icon">
            <img src="<?php echo $block->getViewFileUrl('images/credit-card-icon.png'); ?>" alt="<?php echo $this->escapeHtml(__('credit-card')); ?>">
        </div>
        <div class="description">
            <h4><?php echo __('Secure Payment'); ?></h4>
            <p><?php echo __('Our Confident Client'); ?></p>
        </div>
    </div>
    <div class="advantage support">
        <div class="icon">
            <img src="<?php echo $block->getViewFileUrl('images/technical-support-icon.png'); ?>" alt="<?php echo $this->escapeHtml(__('technical-support')); ?>">
        </div>
        <div class="description">
            <h4><?php echo __('24/7 Support'); ?></h4>
            <p><?php echo __('Our Confident Client'); ?></p>
        </div>
    </div>
</div>


