<!-- Featured Products Section -->
<section class="featured-products">
    <div class="container">
        <div class="product product-1">
            <div class="wrap">
                <h3><?php echo $block->escapeHtml(__('Try X-Balls')); ?></h3>
                <p><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet consectetur. Morbi aenean convallis fringilla quam lectus.')); ?></p>
                <a href="<?php echo $block->getCategoryById(20)->getUrl(); ?>" class="btn-primary"><?php echo $block->escapeHtml(__('Shop Now')); ?></a>
            </div>
        </div>
        <div class="product product-2">
            <div class="wrap wrap-text-white">
                <h3><?php echo $block->escapeHtml(__('our jupiters')); ?></h3>
                <p><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet consectetur. Morbi aenean convallis fringilla quam lectus.')); ?></p>
                <a href="<?php echo $block->getCategoryById(20)->getUrl(); ?>" class="btn-primary btn-primary-white"><?php echo $block->escapeHtml(__('Shop Now')); ?></a>
            </div>
        </div>
        <div class="product product-3">
            <div class="wrap">
                <h3><?php echo $block->escapeHtml(__('click &play')); ?></h3>
                <p><?php echo $block->escapeHtml(__('Lorem ipsum dolor sit amet consectetur. Morbi aenean convallis fringilla quam lectus.')); ?></p>
                <a href="<?php echo $block->getCategoryById(20)->getUrl(); ?>" class="btn-primary"><?php echo $block->escapeHtml(__('Shop Now')); ?></a>
            </div>
        </div>
    </div>
</section>
