<!-- Happy Customer Section -->
<section class="happy-customer">
    <div class="container">
        <h2><?php echo $block->escapeHtml(__('Happy Customer')); ?></h2>
        <div class="testimonials">
            <div class="testimonial">
                <p><?php echo $block->escapeHtml(__('“We are working hard to provide the best quality for you and we hope that you and your friends enjoy your new speevers X-balls!”')); ?></p>
                <p>- <?php echo $block->escapeHtml(__('Ashraf Annie, Our Customer Chief')); ?></p>
            </div>
            <div class="testimonial">
                <p><?php echo $block->escapeHtml(__('“We are working hard to provide the best quality for you and we hope that you and your friends enjoy your new speevers X-balls!”')); ?></p>
                <p>- <?php echo $block->escapeHtml(__('Ashraf Annie, Our Customer Chief')); ?></p>
            </div>
        </div>
    </div>
</section>
