<div class="header-container">
    <div class="top-bar">FREE RETURNS. STANDARD SHIPPING ORDERS $99+</div>
<!--    <div class="wrap"></div>-->
    <div class="container">
        <div class="logo">
            <img src="<?php echo $block->getViewFileUrl('images/logo.png'); ?>" alt="Speevers Logo">
        </div>
        <div class="top-links">
            <a href="#" class="search-link">
                <img src="<?= $this->getViewFileUrl('images/icon-search.png') ?>" alt="Search Icon">
            </a>
            <a href="#" class="like-link">
                <img src="<?= $this->getViewFileUrl('images/icon-heart.png') ?>" alt="Heart Icon">
            </a>
            <a href="#" class="login-link">Login</a>
            <a href="#" class="reg-link">
                <span class="reg-link-text">Register</span>
            </a>
            <a href="#" class="cart-link">
                <span class="cart-link-wrap">
                    <img class="cart-link-icon" src="<?= $this->getViewFileUrl('images/icon-cart.png') ?>" alt="Heart Icon">
                    <span class="cart-link-text">View Cart</span>
                </span>
            </a>
        </div>
    </div>

    <nav class="main-nav">
        <div class="container">
            <ul>
                <li><a href="#">Modular Juggling Props</a></li>
                <li><a href="#">Juggling Prop Configurator</a></li>
                <li><a href="#">Balls</a></li>
                <li><a href="#">Flow Arts</a></li>
                <li><a href="#">Light & Fire</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </div>
    </nav>

</div>

