<!-- Footer Bottom -->
<div class="footer-bottom">
    <p class="copy">© Copyright <?php echo date('Y'); ?></p>
    <div class="pay-sys">
        <p><?php echo __('Accept Payment'); ?></p>
        <div class="cards">
            <img src="<?php echo $block->getViewFileUrl('images/icon-stripe.png'); ?>" alt="Stripe">
            <img src="<?php echo $block->getViewFileUrl('images/paypal-logo.jpg'); ?>" alt="PayPal">
            <img src="<?php echo $block->getViewFileUrl('images/visa-logo.png'); ?>" alt="Visa">
            <img src="<?php echo $block->getViewFileUrl('images/mastercard-logo.png'); ?>" alt="Mastercard">
            <img src="<?php echo $block->getViewFileUrl('images/express-logo.png'); ?>" alt="American Express">
        </div>
    </div>
</div>
