<div class="socials fc-socials">
    <a href="https://www.instagram.com/" target="_blank">
        <img src="<?php echo $block->getViewFileUrl('images/icon-instagram.png'); ?>" alt="Instagram">
    </a>

    <a href="https://www.facebook.com/" target="_blank">
        <img src="<?php echo $block->getViewFileUrl('images/icon-facebook.png'); ?>" alt="Facebook">
    </a>

    <a href="https://www.youtube.com/" target="_blank">
        <img src="<?php echo $block->getViewFileUrl('images/icon-youtube.png'); ?>" alt="YouTube">
    </a>
</div>

