<!-- Customer Service Column -->
<div class="footer-column right">
    <h4><?php echo __('Customer Service'); ?></h4>
    <ul>
        <li><a href="<?php echo $this->getUrl('shipping-delivery'); ?>"><?php echo __('Shipping & Delivery'); ?></a></li>
        <li><a href="<?php echo $this->getUrl('about-us'); ?>"><?php echo __('About Us'); ?></a></li>
        <li id="privacy-policy">
            <a href="<?php echo $this->getUrl('privacy-policy-cookie-restriction-mode'); ?>"><?php echo __('Privacy &amp; Cookies Policy'); ?></a>
        </li>
    </ul>
</div>
