<div class="logo-container">
    <div class="footer-logo">
        <img src="<?php echo $block->getViewFileUrl('images/logo-footer.png'); ?>" alt="<?php echo $this->escapeHtml(__('Speevers Logo')); ?>">
    </div>
    <div class="socials">
        <h4><?php echo __('Find us here'); ?></h4>
        <a href="https://www.instagram.com/" target="_blank">
            <img src="<?php echo $block->getViewFileUrl('images/icon-instagram.png'); ?>" alt="Instagram">
        </a>

        <a href="https://www.facebook.com/" target="_blank">
            <img src="<?php echo $block->getViewFileUrl('images/icon-facebook.png'); ?>" alt="Facebook">
        </a>

        <a href="https://www.youtube.com/" target="_blank">
            <img src="<?php echo $block->getViewFileUrl('images/icon-youtube.png'); ?>" alt="YouTube">
        </a>
    </div>
</div>
