<!-- Categories Section -->

<section class="categories">
<!--    <div class="container">-->
        <div class="category-icons">
            <div class="category">
                <a href="<?php echo $block->getCategoryById(20)->getUrl(); ?>">
                    <img src="<?php echo $block->getViewFileUrl('images/icon-balls.png'); ?>" alt="<?php echo $block->escapeHtml(__('Balls')); ?>">
                    <p><?php echo $block->escapeHtml(__('Balls')); ?></p>
                </a>
            </div>
            <div class="category">
                <a href="<?php echo $block->getCategoryById(38)->getUrl(); ?>">
                    <img src="<?php echo $block->getViewFileUrl('images/icon-juggling.png'); ?>" alt="<?php echo $block->escapeHtml(__('Juggling Props')); ?>">
                    <p><?php echo $block->escapeHtml(__('Juggling Props')); ?></p>
                </a>
            </div>
            <div class="category">
                <a href="<?php echo $block->getCategoryById(3)->getUrl(); ?>">
                    <img src="<?php echo $block->getViewFileUrl('images/icon-flow.png'); ?>" alt="<?php echo $block->escapeHtml(__('Flow Arts')); ?>">
                    <p><?php echo $block->escapeHtml(__('Flow Arts')); ?></p>
                </a>
            </div>
            <div class="category">
                <a href="<?php echo $block->getCategoryById(9)->getUrl(); ?>">
                    <img src="<?php echo $block->getViewFileUrl('images/icon-lights.png'); ?>" alt="<?php echo $block->escapeHtml(__('Lights & Fire')); ?>">
                    <p><?php echo $block->escapeHtml(__('Light & Fire')); ?></p>
                </a>
            </div>
            <div class="category">
                <a href="<?php echo $block->getCategoryById(45)->getUrl(); ?>">
                    <img src="<?php echo $block->getViewFileUrl('images/icon-bags.png'); ?>" alt="<?php echo $block->escapeHtml(__('Bags & Cases')); ?>">
                    <p><?php echo $block->escapeHtml(__('Bags & Cases')); ?></p>
                </a>
            </div>
        </div>
<!--    </div>-->
</section>
