<!-- Quick Links Column -->
<div class="footer-column">
    <h4><?php echo __('Quick Links'); ?></h4>
    <ul id="footer-content-links">
        <li><a href="<?php echo $this->getUrl('terms-of-services'); ?>"><?php echo __('Terms Of Services'); ?></a></li>
        <li id="footer-order-history"><a href="<?php echo $this->getUrl('sales/order/history'); ?>"><?php echo __('Order History'); ?></a></li>
        <li id="footer-my-account">
            <a href="<?php echo $this->getUrl('customer/account'); ?>"><?php echo __('My Account'); ?></a>
        </li>
    </ul>
</div>
